name: Feature Request
description: Suggest a code change or feature implementation
title: 'Feature Request: '
labels: 
  - enhancement
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the feature does.
      placeholder: Describe the changes...

  - type: input
    id: related_issue
    attributes:
      label: Related Issue
      description: Please link to the issue this feature request addresses.
      placeholder: Provide the issue link...

  - type: checkboxes
    id: type_of_change
    attributes:
      label: Type of Change
      description: Select the type of change.
      options:
        - label: New feature (non-breaking change which adds functionality)
        - label: Breaking change (fix or feature that would cause existing functionality to not work as expected)
        - label: Documentation update
        - label: Environment Variables update
        - label: MySQL Database update
        - label: REDIS Database update

  - type: checkboxes
    id: checklist
    attributes:
      label: Code Complete Checklist
      description: Ensure all tasks are complete. Please do not fill these out at the time of the issue submission but after code for the feature is complete.
      options:
        - label: My code follows the style guidelines of this project
        - label: I have performed a self-review of my own code
        - label: I have commented my code, particularly in hard-to-understand areas
        - label: I have made corresponding changes to the documentation
        - label: My changes generate no new warnings
        - label: I have added tests that prove my fix is effective or that my feature works
        - label: New and existing unit tests pass locally with my changes
        - label: Any dependent changes have been merged and published in downstream modules

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Add any other information or screenshots that may help explain the feature request here.
      placeholder: Provide additional information...
