name: Hotfix
description: Submit an urgent bug fix
title: 'Hotfix: '
labels: 
  - hotfix
assignees: []

body:
  - type: textarea
    id: issue_description
    attributes:
      label: Issue Description
      description: A clear and concise description of the issue that requires an urgent fix.
      placeholder: Describe the issue...

  - type: textarea
    id: root_cause
    attributes:
      label: Root Cause
      description: Describe the root cause of the issue.
      placeholder: Describe the root cause...

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: A clear and concise description of what you have done to fix the issue.
      placeholder: Describe the solution...

  - type: checkboxes
    id: risk_level
    attributes:
      label: Risk Level
      description: Select the risk level of the hotfix.
      options:
        - label: Low (minimal risk of causing other issues)
        - label: Medium (moderate risk of causing other issues)
        - label: High (high risk of causing other issues)

  - type: textarea
    id: testing
    attributes:
      label: Testing
      description: Describe the tests you have performed to ensure the fix works as expected.
      placeholder: Describe the testing...

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Add any other context or information about the fix here.
      placeholder: Provide additional information...
