name: Task
description: Template for creating a new task
title: 'Task: '
labels: ["task"]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the task.
      placeholder: Enter the task description here...
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Select the severity level of the task.
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Add any additional notes related to the task.
      placeholder: Enter any additional notes here...

  - type: checkboxes
    id: task_areas
    attributes:
      label: Task Areas
      description: Select the areas this task pertains to.
      options:
        - label: Frontend
        - label: Backend
        - label: Database
        - label: Documentation
        - label: Testing
        - label: Deployment

  - type: input
    id: due_date
    attributes:
      label: Due Date
      description: Select the due date for this task.
      placeholder: Select a due date
